"""
Data Audit Schema

Pydantic models for the data manifest JSON output.
Reusable in tests, notebooks, and CI checks.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SplitStats(BaseModel):
    """Statistics for a single data split (train/val/test)."""

    count: int = 0
    by_type: Dict[str, int] = Field(default_factory=dict)


class QAPairStats(BaseModel):
    """Statistics for chart QA pairs."""

    total: int = 0
    by_type: Dict[str, int] = Field(default_factory=dict)
    coverage_pct: float = 0.0


class SLMTrainingStats(BaseModel):
    """Statistics for SLM training dataset."""

    total: int = 0
    by_type: Dict[str, int] = Field(default_factory=dict)
    version: str = ""


class BenchmarkStats(BaseModel):
    """Statistics for benchmark annotations."""

    total_annotated: int = 0
    by_type: Dict[str, int] = Field(default_factory=dict)
    total_images: int = 0


class IntegrityReport(BaseModel):
    """Data integrity check results."""

    broken_images: int = 0
    missing_labels: int = 0
    orphaned_files: int = 0
    details: List[str] = Field(default_factory=list)


class DiffReport(BaseModel):
    """Difference from previous manifest."""

    added: int = 0
    removed: int = 0
    changed_types: Dict[str, int] = Field(default_factory=dict)
    previous_manifest: Optional[str] = None


class DataManifest(BaseModel):
    """
    Complete data audit manifest.

    Generated by scripts/data_management/audit.py
    Saved to output/data_manifest.json
    """

    generated_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    version: str = "v3"
    project_root: str = ""

    # Dataset splits (academic dataset)
    splits: Dict[str, SplitStats] = Field(default_factory=dict)

    # QA pairs
    qa_pairs: QAPairStats = Field(default_factory=QAPairStats)

    # SLM training data
    slm_training: SLMTrainingStats = Field(default_factory=SLMTrainingStats)

    # Benchmark data
    benchmark: BenchmarkStats = Field(default_factory=BenchmarkStats)

    # Stage 3 features
    stage3_features: Dict[str, Any] = Field(default_factory=dict)

    # Integrity
    integrity: IntegrityReport = Field(default_factory=IntegrityReport)

    # Diff from previous
    diff_from_previous: Optional[DiffReport] = None

    # Summary
    total_chart_images: int = 0
    total_annotations: int = 0
